# 디플로이먼트 생성
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: dnjswo890/test:nodejs
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "500M"
            cpu: "3"
          requests:
            memory: "500M"
            cpu: "3"
---
# 서비스 생성
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  ports:
  - name: nodejs
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs
  type: LoadBalancer
